# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03c5be834c43961423dc03d3e48cb2d4884e56c03a1e11f7c38776ba95c8ebea986723c7b69c0b259fc67473b9b1543d6ba9ee0a8802840645f553c2457b705d

test:
  secret_key_base: 2dc4b296278a75545b3e5ab156df02b7bd16745a614d3618a4c6c76c6dbad30351daa4195b98a325c5993a79dd1d36e2564ef9b0f2c66a9102c0413ca2d400b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
